### PR TITLE
add (optional, configurable) back button in details view, add state-service

### PR DESCRIPTION
**Pull request by mangei**

### CODE REVIEW

**Comment by tscheinecker** [comment]
i don't understand the necessity for this, especially the directive

all it has to do is call a real browser back, the way it works now it actually creates a new history entry and i can reverse the back action by clicking the browser back button

i'm not really inclined to include this into the base-code without a very good reason

:-1:

**Comment by tscheinecker** [comment]
in addition: have a look at http://christopherthielen.github.io/ui-router-extras/#/previous

**Comment by mangei** [comment]
I will investigate, why we did it this way...

**Comment by tscheinecker** [comment]
closing for now, if there really is an compelling reason for such a feature open an appropriate ticket

**Pull request closed without merging**
